---
- name: Install deps 1/2
  become: true
  apt: name=python3-pip state=present
- name: Install deps 2/2
  pip:
    name:
      - docker
      - docker-compose
    state: present
  changed_when: false

- name: ensure destination for compose file exists
  ansible.builtin.file:
    path: '{{ docker_compose_generator_output_path }}'
    state: directory
  tags: docker-compose

- name: write docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ docker_compose_generator_output_path }}/docker-compose.yml'
    owner: '{{ docker_compose_generator_uid }}'
    group: '{{ docker_compose_generator_gid }}'
  tags: docker-compose

- name: Create and start services
  community.general.docker_compose:
    project_src: '~'
    build: false
    pull: true
  tags: docker-compose

- name: Prune old images and volumes (including non-dangling images)
  community.general.docker_prune:
    images: true
    images_filters:
      dangling: false
      until: 7m
    volumes: yes
  tags: docker-compose, test
