---
- hosts: localhost
  connection: local
  tasks:
  - name: Create inventory.yml
    include_role:
      name: inventory_generator
    tags: always

  - meta: refresh_inventory
    tags: always

- hosts: all
  become: true
  tasks:
    # - name: Ensure ansible user accepts the SSH key
      # authorized_key:
        # user: '{{ ansible_user }}'
        # key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        # state: present

    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        cache_valid_time: 86400     # 86400 = One day
        upgrade: dist
        autoremove: true
        purge: true


- hosts: casaesperanza
  vars:
    dirs_to_backup:
      - config/caddy
      - config/homeassistant
      - config/homeassistant_db
      - config/mosquitto
      - config/node-red
      - wireguard
  tasks:
    - name: Create docker-compose
      include_role:
        name: docker_compose_generator
      tags: docker-compose

- hosts: caleserver
  tasks:
    - name: Cron jobs
      import_role:
        name: cron
      become: true
      tags: cron

    - name: Create docker-compose
      include_role:
        name: docker_compose_generator
      tags: docker-compose


- hosts: localhost
  connection: local
  tasks:
    - name: Remove inventory.yml
      file:
        path: inventory.yml
        state: absent
      changed_when: false
      tags: always
...
