---
name: 'Yamllint GitHub Actions'
on:
  - pull_request
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Trailing spaces'
        uses: harupy/find-trailing-whitespace@master
      - name: 'yamllint'
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              truthy:
                allowed-values: ['true', 'false', 'on']
              line-length:
                max: 160
                allow-non-breakable-inline-mappings: true
                level: warning
              document-start:
                present: true
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
